apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Name }}-monitor
  namespace: {{ .Namespace }}
  labels:
    app: {{ .Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Name }}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true