apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-cluster-config
  namespace: kube-system
data:
  cluster.yaml: |
    cluster:
      name: "${CLUSTER_NAME}"
      provider: "eks"
      region: "${AWS_REGION}"

    monitoring:
      enabled: true
      namespace: "monitoring"

    karpenter:
      enabled: true
      provisioner:
        ttlSecondsAfterEmpty: 30
        requirements:
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: ["spot", "on-demand"]
          - key: "node.kubernetes.io/instance-type"
            operator: In
            values: ["m5.large", "m5.xlarge", "m5.2xlarge"]